import { TabWidget, Button } from "std-widgets.slint";

export component AppWindow inherits Window {
    width: 800px;
    height: 600px;
    TabWidget {
        Tab {
            title: "Play";
            HorizontalLayout {
                VerticalLayout {
                    Button {
                        text: "Game 1";
                    }
                    Button {
                        text: "Game 2";
                    }
                    Button {
                        text: "Game 2";
                    }
                }
                Button {
                    text: "Play";
                }
            }
        }
        Tab {
            title: "Manage";
            GridLayout {

            }
        }
    }
}