import { TabWidget, Button, ListView } from "std-widgets.slint";

export component AppWindow inherits Window {
    width: 800px;
    height: 600px;
    TabWidget {
        Tab {
            title: "Play";
            HorizontalLayout {
                VerticalLayout {
                    ListView {
                        width: 200px;
                        for data in [
                            { text: "Game 1" },
                            { text: "Game 2" },
                            { text: "Game 3" },
                        ] : Button {
                            text: data.text;
                        }
                    }
                }
                Button {
                    text: "Play";
                }
            }
        }
        Tab {
            title: "Manage";
            GridLayout {

            }
        }
    }
}