import { TabWidget, Button, ListView } from "std-widgets.slint";

export component AppWindow inherits Window {

    in property <int> number-of-buttons;

    width: 800px;
    height: 600px;

    TabWidget {
        Tab {
            title: "Play";
            HorizontalLayout {
                VerticalLayout {
                    ListView {
                        width: 200px;
                        for data in number-of-buttons : Button {
                            text: "Game";
                        }
                    }
                }
                Button {
                    text: "Play";
                }
            }
        }
        Tab {
            title: "Manage";
            GridLayout {

            }
        }
    }
}